### ISSUE TITLE
Re. the policy head in ICRT

### ISSUE THREAD

**Issue by ShahRutav** [Max-Fu/icrt#2]
Hi, thanks a lot for open-sourcing the work!

I noticed that the default policy head in ICRT is a simple MLP ([here](https://github.com/Max-Fu/icrt/blob/fd5f2fb1305f466b55f7aa49cf1b0109fa832adc/icrt/util/args.py#L123)). Did you experiment with other policy heads w/ ICRT architecture that can better accommodate multimodal action distribution due to human teleoperated trajectories?

**Comment by Max-Fu** [comment]
We have tried [GMM](https://github.com/Max-Fu/icrt/blob/fd5f2fb1305f466b55f7aa49cf1b0109fa832adc/icrt/models/policy/action_head.py#L107) but we barely see any improvements over default MLP on the test tasks. We also have tried [diffusion](https://github.com/Max-Fu/icrt/blob/fd5f2fb1305f466b55f7aa49cf1b0109fa832adc/icrt/models/policy/action_head.py#L245), but dataset statistics are needed to normalize the action. We haven't gotten diffusion to work with the model yet. 

You can pick the action head by updating the [args](https://github.com/Max-Fu/icrt/blob/fd5f2fb1305f466b55f7aa49cf1b0109fa832adc/icrt/util/args.py#L123). 

Let me know you have any questions!

**Comment by ShahRutav** [comment]
Interesting. I expected GMM to perform better due to the multimodal action distribution in human demonstrations, especially DROID.
Thanks for the response!

**Comment by Max-Fu** [comment]
No problem!
